store/config/routes.rb
Rails.application.routes.draw do
  get "login/new"
  root "home#index"
   
  resources :accounts, only: [:new, :create, :index]
  get "accounts/verify_code", to: "accounts#verify_code" , as: "verify_account"
  post "accounts/verify_code", to: "accounts#process_verification"
  post 'accounts/resend_email', to: 'accounts#resend_email', as: 'resend_account_email'

  resources :forgot_password, only: [:new, :create] do
    collection do
      get :verify_code
      post :process_verification
      get :update_password
      post :process_update_password
      
    end 
  end 

  get "login/account", to: "login#account", as: "login_account_page"
  get 'login/admin_account', to: 'login#admin_account', as: 'admin_account'
  post "login/account", to: "login#account", as: "login_account"
  delete 'logout_account', to: 'login#logout_account', as: 'logout_account'

  #send here after login
  get "login/profile", to: "login#profile", as: "profile_login"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

store/app/controllers/forgot_password_controller.rb
class ForgotPasswordController < ApplicationController
  def new
  end

  def create
    account = Account.find_by(email: params[:email])

    if account && account.verified == true
      session[:verification_code] = generate_verification_code
      session[:verification_code_expires_at] = 210.seconds.from_now
     
      if account.update(verification_code: session[:verification_code])
        begin
          AccountMailer.verification_email(account.email, account.verification_code).deliver_now
          
          redirect_to verify_code_forgot_password_index_path
          flash[:alert] = "Verification sent."
        rescue => e 
          flash[:alert] = "Sending email failed. Try again."
          redirect_to new_forgot_password_path
        end
      else
        flash[:alert] = "Failed to update account. Try again."
        redirect_to new_forgot_password_path
      end
    else
      flash[:alert] = "Email not found"
      redirect_to new_forgot_password_path	
    end
  end

  def process_verification
    input_code = params[:input_code]
    account = Account.find_by(verification_code: session[:verification_code])

    if account.nil?
      flash[:notice] = "Verification expired."
      session[:verification_code] = nil
      session[:verification_code_expires_at] = nil

      redirect_to new_forgot_password_path
    end

    if session[:verification_code_expires_at] == nil || session[:verification_code_expires_at] < Time.current
      flash[:notice] = "Verification expired."
      session[:verification_code] = nil
      session[:verification_code_expires_at] = nil

      redirect_to new_forgot_password_path	
      return
    end

    if account && account.verification_code == input_code
      session[:reset_password_id] = account.id
      session[:verification_code] = nil
      session[:verification_code_expires_at] = nil

      redirect_to update_password_forgot_password_index_path
    else
      flash[:alert] = "Verification code incorrect. Try again."
     redirect_to verify_code_forgot_password_index_path
    end
  end

  def update_password
    @account = Account.new
  end

  def process_update_password
    @account = Account.find_by(id: session[:reset_password_id])

    if @account.id.present?
      if @account.update(new_password_params.merge(verification_code: nil))
        flash[:notice] = "Password changed successfully."
        session[:reset_password_id] = nil
        redirect_to root_path
      else
        flash[:notice] = @account.errors.full_messages.join(", ")
        redirect_to update_password_forgot_password_index_path
      end
    else
      flash[:notice] = "Password change failed."
      redirect_to update_password_forgot_password_index_path
    end
  end

  private

  def new_password_params
   params.require(:account).permit(:password, :password_confirmation)
  end

  def generate_verification_code
    loop do
      code = rand(100000..999999).to_s
        return code unless Account.exists?(verification_code: code)
    end     
  end
  
end

store/app/helpers/forgot_password_helper.rb
module ForgotPasswordHelper
end

store/app/views/forgot_password/create.html.erb
<h1>ForgotPassword#create</h1>
<p>Find me in app/views/forgot_password/create.html.erb</p>

store/app/views/forgot_password/new.html.erb
<h1>Forgot password</h1>


<% if flash[:notice] %>
    <div class = "alert alert-sucess">
        <%= flash[:notice] %>
    </div>
<% end %>
<% if flash[:alert] %>
    <div class = "alert alert-sucess">
        <%= flash[:alert] %>
    </div>
<% end %>

<%= form_with url: forgot_password_index_path, local: true, data: { turbo: false } do |form| %>
  <%= form.label :email, "Email account" %>
  <%= form.text_field :email %>
  <%= form.submit "Send Verification" %>
<% end %>

store/app/views/forgot_password/update_password.html.erb
<h1>Enter your new password</h1>

<% flash.each do |type, message| %>
  <% if message.present? %>
    <div>
      <%= message %>
    </div>
  <% end %>
<% end %>


<%= form_with model: @account, url: process_update_password_forgot_password_index_path, local: true, data: {turbo: false} do |forms| %>

    <%= forms.label :password, "New password" %>
    <%= forms.text_field :password %>

    <%= forms.label :password_confirmation, "Confirm new password" %>
    <%= forms.password_field :password_confirmation  %>

    <%= forms.submit "Change password" %>
<% end %>

store/app/views/forgot_password/verify_code.html.erb
<h1>Verification</h1>


<% if flash[:alert] %>
    <div>
        <%= flash[:alert] %>
    </div>
<% end %>

<%= form_with url: process_verification_forgot_password_index_path, local: true, data: {turbo: false} do |forms| %>

    <%= forms.label :input_code, "Verification Code" %>
    <%= forms.text_field :input_code %>

    <%= forms.submit "Verify"%>
<% end %>