store/config/routes.rb
Rails.application.routes.draw do
  get "login/new"
  root "home#index"
   
  resources :accounts, only: [:new, :create, :index]
  get "accounts/verify_code", to: "accounts#verify_code" , as: "verify_account"
  post "accounts/verify_code", to: "accounts#process_verification"
  post 'accounts/resend_email', to: 'accounts#resend_email', as: 'resend_account_email'

  resources :forgot_password, only: [:new, :create] do
    collection do
      get :verify_code
      post :process_verification
      get :update_password
      post :process_update_password
      
    end 
  end 

  get "login/account", to: "login#account", as: "login_account_page"
  get 'login/admin_account', to: 'login#admin_account', as: 'admin_account'
  post "login/account", to: "login#account", as: "login_account"
  delete 'logout_account', to: 'login#logout_account', as: 'logout_account'

  #send here after login
  get "login/profile", to: "login#profile", as: "profile_login"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

store/app/models/account.rb
class Account < ApplicationRecord
    scope :unverified_expired, -> { where(verified: false).where("created_at < ?", 3.days.ago) }

    validates :email, format: {with: URI::MailTo::EMAIL_REGEXP, message: "Not a valid email address."}
    # validates :username, uniqueness: { message: "Email already exist."}

    validates :password, length: { minimum: 8, message: "Password too short. Minimun of 8 characters."}
    validates :password, confirmation: { message: "Password does not match."}
    validates :password, format: { with: /\A(?=.*[0-9])(?=.*[^A-Za-z0-9]).+\z/, message: "Password must contain at least 1 number and 1 symbol."}
end

store/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    @account = Account.new
  end

def create
  @account = Account.find_by(email: account_params[:email])

  if @account.present?
    if @account.verified?
      flash[:alert] = "Email already exists."
      redirect_to new_account_path and return
    else
      @account.assign_attributes(account_params)
      @account.verification_code = generate_verification_code

      if @account.save
        set_verification_session(@account)
        begin
          AccountMailer.verification_email(@account.email, @account.verification_code).deliver_now
          flash[:notice] = "Verification email sent again. Please verify your account."
          redirect_to verify_account_path and return
        rescue => e
          flash[:alert] = "Sending email failed. Try again."
          redirect_to new_account_path and return
        end
      else
        redirect_to new_account_path and return
      end
    end
  else
    # Not found, create new
    @account = Account.new(account_params)
    @account.verification_code = rand(100000..999999).to_s
    if @account.save
      set_verification_session(@account)
      begin
        AccountMailer.verification_email(@account.email, @account.verification_code).deliver_now
        flash[:notice] = "Verification email sent again. Please verify your account."
        redirect_to verify_account_path and return
      rescue => e
        flash[:alert] = "Sending email failed. Try again."
        redirect_to new_account_path and return
      end
    else
      redirect_to new_account_path and return
    end
  end
end


def resend_email
  @account = Account.find_by(id: session[:account_id])

  if @account.nil?
    flash[:alert] = "Account not found or session expired. Please sign up again."
    redirect_to new_account_path
    return
  end

  if @account.verified?
    flash[:alert] = "Account already verified."
    redirect_to root_path
    return
  end


   begin
          AccountMailer.verification_email(@account.email, @account.verification_code).deliver_now
          flash[:notice] = "Verification email sent again. Please verify your account."
          redirect_to verify_account_path and return
        rescue => e
          flash[:alert] = "Sending email failed. Try again."
          @account = Account.new(account_params)
          render :new and return
        end

  if @account.save
    set_verification_session(@account)

    begin    
      AccountMailer.verification_email(@account.email, @account.verification_code).deliver_now
      flash[:notice] = "Verification email resent. Please check your email."
      redirect_to verify_account_path
    rescue 
    end
    

  else
    flash[:alert] = "Could not resend email. Please try again."
    redirect_to new_account_path
  end
end


def verify_code
end

def process_verification
  input_code = params[:input_verification]
  @account = Account.find_by(id: session[:account_id])

  if session[:verification_code_expires_at].nil? || session[:verification_code_expires_at] < Time.current
    session[:account_id] = nil
    session[:verification_code] = nil
    session[:verification_code_expires_at] = nil

    flash[:alert] = "Verification code has expired. Please sign up again."
    redirect_to new_account_path  
  elsif @account.nil?
    flash.now[:alert] = "Verification failed. Try again."
    render :verify_code
  elsif @account.verification_code == input_code

    if @account.update(verified: true, verification_code: nil) 
      session[:account_id] = nil
      session[:verification_code] = nil
      session[:verification_code_expires_at] = nil
      
      flash[:notice] = "Created account successfully."
      redirect_to root_path
    else
      flash.now[:alert] = "Verification failed. Try again."
      render :verify_code
    end
  else
    flash.now[:alert] = "Incorrect verification code. Please try again."
    render :verify_code
  end
end

def index
  redirect_to new_account_path
end

  private

  def account_params
    params.require(:account).permit(:email, :username, :password, :password_confirmation)
  end

 def set_verification_session(account)
  session[:account_id] = account.id
  session[:verification_code] = account.verification_code
  session[:verification_code_expires_at] = 180.seconds.from_now
end

  def generate_verification_code
    loop do
      code = rand(100000..999999).to_s
        return code unless Account.exists?(verification_code: code)
    end     
  end

end

store/app/helpers/accounts_helper.rb
module AccountsHelper
end

store/app/views/accounts/create.html.erb
<h1>Accounts#create</h1>
<p>Find me in app/views/accounts/create.html.erb</p>

store/app/views/accounts/new.html.erb
<h1>Create new account</h1>
<h2>Fill up the forms</h2>

<% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

<%= form_with model: @account, url: accounts_path, local: true, data: { turbo: false } do |f| %>
  <div>
    <%= f.label :email, "Email account" %><br>
    <% if @account.errors[:email].any? %>
      <ul>
        <% @account.errors[:email].each do |msg| %>
          <li class="text-danger"><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    <%= f.text_field :email, autocomplete: "email", required: true %>
  </div>
  <div>
    <%= f.label :username %><br>
    <% if @account.errors[:username].any? %>
      <ul>
        <% @account.errors[:username].each do |msg| %>
          <li class="text-danger"><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    <%= f.text_field :username, autocomplete: "username", required: true %>
  </div>
  <div>
    <%= f.label :password %><br>
    <% if @account.errors[:password].any? %>
      <ul>
        <% @account.errors[:password].each do |msg| %>
          <li class="text-danger"><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    <%= f.text_field :password, autocomplete: "new-password", required: true %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <% if @account.errors[:password_confirmation].any? %>
      <ul>
        <% @account.errors[:password_confirmation].each do |msg| %>
          <li class="text-danger"><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    <%= f.password_field :password_confirmation, autocomplete: "new-password", required: true %>
  </div>
  <%= f.submit "Create account" %>
<% end %>

<%= button_to "Back to home page", root_path, method: :get %>

store/app/views/accounts/verify_code.html.erb
<h1>Verification</h1>

<h2>Enter your verification number</h2>

<% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<%= form_with url: accounts_verify_code_path, local: true, data: { turbo: false } do |forms| %>
  <%= forms.label :input_verification %>
  <%= forms.text_field :input_verification %>
  <%= forms.submit "Verify Code" %>
<% end %>

<%= button_to "Resend Verification Email", resend_account_email_path, method: :post %>