store/config/routes.rb
Rails.application.routes.draw do
  get "login/new"
  root "home#index"
   
  resources :accounts, only: [:new, :create, :index]
  get "accounts/verify_code", to: "accounts#verify_code" , as: "verify_account"
  post "accounts/verify_code", to: "accounts#process_verification"
  post 'accounts/resend_email', to: 'accounts#resend_email', as: 'resend_account_email'

  resources :forgot_password, only: [:new, :create] do
    collection do
      get :verify_code
      post :process_verification
      get :update_password
      post :process_update_password
      
    end 
  end 

  get "login/account", to: "login#account", as: "login_account_page"
  get 'login/admin_account', to: 'login#admin_account', as: 'admin_account'
  post "login/account", to: "login#account", as: "login_account"
  delete 'logout_account', to: 'login#logout_account', as: 'logout_account'

  #send here after login
  get "login/profile", to: "login#profile", as: "profile_login"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

store/app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :require_login, only: [:profile, :logout_account, :admin_account ]



  def account
    account = Account.find_by(email: params[:email])
    account_password = params[:password]

    if account
      if account.password == account_password
        if account.roles == "a" 
          session[:login_id] = account.id
          redirect_to profile_login_path
        else
          session[:login_id] = account.id
          redirect_to admin_account_path
        end
      else
        flash[:notice] = "Password incorrect"
        render :account
      end
    else
      flash[:notice] = "Email incorrect"
      render :account
    end
  end

  def logout_account
    session[:login_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to root_path
  end

  private

  def require_login
    unless session[:login_id]
      flash[:notice] = "Please login first"
      redirect_to root_path
    end
  end
end

store/app/helpers/login_helper.rb
module LoginHelper
end

store/app/views/login/account.html.erb
<h1>Login#new</h1>
<p>Find me in app/views/login/new.html.erb</p>

<%= form_with url: login_account_path, local: true, data: { turbo: false } do |forms| %>

    <div>
        <%= forms.label :email, "Email account" %>
        <%= forms.text_field :email %>
    </div>

    <div>
        <%= forms.label :password%>
        <%= forms.password_field :password %>
    </div>

    <%= forms.submit "Login" %>
<% end %>

store/app/views/login/admin_account.html.erb
<h1>Hi admin</h1>
<%= button_to 'Logout', logout_account_path, method: :delete, class: 'btn btn-danger' %>

store/app/views/login/profile.html.erb
<h1>this is your account</h1>

<%= button_to 'Logout', logout_account_path, method: :delete, class: 'btn btn-danger' %>